/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ericheitmuller;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Miner miner = new Miner(
                1, 5, 5, 0,
                5, new TestState1()
        );
        for(int i = 0; i < 10; i++) {
            miner.update();
            Thread.sleep(500);
        }
    }
}
